# Generated by Django 4.1 on 2022-08-25 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('current', models.BooleanField(default=False)),
                ('content', models.BinaryField()),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('name', models.CharField(default='', max_length=200)),
                ('previous', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ravnica.season')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('round', models.IntegerField(choices=[(1, 'Round One'), (2, 'Round Two'), (3, 'Round Three'), (4, 'Round Four'), (5, 'Round Five'), (6, 'Round Six'), (7, 'Round Seven'), (8, 'Round Eight'), (9, 'Round Nine'), (10, 'Semifinals'), (11, 'Finals'), (12, 'Completed')])),
                ('away', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_set', to='ravnica.deck')),
                ('home', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_set', to='ravnica.deck')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ravnica.season')),
                ('winner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_set', to='ravnica.deck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='deck',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ravnica.guild'),
        ),
    ]
